package common;
/*
 * this enum is used to identify the message type passed between server and client
 */
public enum Protocol {
	CLIENT_CONNECT,
	MAKE_ORDER,
	MAKE_ORDER_SUCCESS,
	MAKE_ORDER_FAIL_NOT_GUIDE,
	MAKE_ORDER_FAIL_TIME,
	MAKE_ORDER_FAIL,
	UPDATE_ORDER,
	UPDATE_ORDER_SUCCESS,
	UPDATE_ORDER_FAILURE,
	CLIENT_DISCONNECT_SERVER,
	CLIENT_DISCONNECT_USER,
	RETURN_ORDER,
	
	GET_PARK_NAMES,
	RETURN_PARK_NAMES_SUCCESS,
	RETURN_PARK_NAMES_FAILURE,
	
	GET_ACTIVE_PARKS,
	ACTIVE_PARKS_RESULT,
	PARKS_UPDATED,

	APPROVE_PARK_PARAMETER_CHANGE_REQUEST,
	REJECT_PARK_PARAMETER_CHANGE_REQUEST,

	PARK_PARAMETER_CHANGE_REQUEST_APPROVED,
	PARK_PARAMETER_CHANGE_REQUEST_REJECTED,
	PARK_PARAMETER_CHANGE_REQUEST_FAILURE
}
