package common;
/*
 * this enum is used to identify the message type passed between server and client
 */
public enum Protocol {
	CLIENT_CONNECT,
	MAKE_ORDER,
	UPDATE_ORDER,
	UPDATE_ORDER_SUCCESS,
	UPDATE_ORDER_FAILURE,
	CLIENT_DISCONNECT_SERVER,
	CLIENT_DISCONNECT_USER,
	RETURN_ORDER,
	GET_ACTIVE_PARKS,
	ACTIVE_PARKS_RESULT,
	PARKS_UPDATED,

	APPROVE_PARK_PARAMETER_CHANGE_REQUEST,
	REJECT_PARK_PARAMETER_CHANGE_REQUEST,

	PARK_PARAMETER_CHANGE_REQUEST_APPROVED,
	PARK_PARAMETER_CHANGE_REQUEST_REJECTED,
	PARK_PARAMETER_CHANGE_REQUEST_FAILURE,
	
	OCCASIONAL_CUSTOMER_ACCESS_REQUEST,
	OCCASIONAL_CUSTOMER_ACCESS_RESPONSE,
	
	EMPLOYEE_LOGIN_REQUEST,
	EMPLOYEE_LOGIN_RESPONSE,

	SEARCH_SUBSCRIBER_REQUEST,
	SEARCH_SUBSCRIBER_RESPONSE,
	REGISTER_GUIDE_REQUEST,
	REGISTER_GUIDE_RESPONSE
}
