package common;
/*
 * this enum is used to identify the message type passed between server and client
 */
public enum Protocol {
	CLIENT_CONNECT,
	MAKE_ORDER,
	MAKE_ORDER_SUCCESS,
	MAKE_ORDER_FAIL_NOT_GUIDE,
	MAKE_ORDER_FAIL_TIME,
	MAKE_ORDER_FAIL_NOT_SUBSCRIBED,
	MAKE_ORDER_FAIL,
	UPDATE_ORDER,
	UPDATE_ORDER_SUCCESS,
	UPDATE_ORDER_FAILURE,
	CLIENT_DISCONNECT_SERVER,
	CLIENT_DISCONNECT_USER,
	RETURN_ORDER,
	CALCULATE_ENTRY_PRICE_REQUEST,
	CALCULATE_ENTRY_PRICE_RESPONSE,
	GET_PARK_VISITOR_COUNTERS_REQUEST,
	PARK_VISITOR_COUNTERS_RESULT,

	UPDATE_PARK_VISITOR_COUNTER_REQUEST,
	PARK_VISITOR_COUNTER_UPDATE_RESULT,

	PARK_VISITOR_COUNTERS_UPDATED,
	
	GET_PARK_NAMES,
	RETURN_PARK_NAMES_SUCCESS,
	RETURN_PARK_NAMES_FAILURE,
	
	GET_ACTIVE_PARKS,
	ACTIVE_PARKS_RESULT,
	PARKS_UPDATED,

	APPROVE_PARK_PARAMETER_CHANGE_REQUEST,
	REJECT_PARK_PARAMETER_CHANGE_REQUEST,

	PARK_PARAMETER_CHANGE_REQUEST_APPROVED,
	PARK_PARAMETER_CHANGE_REQUEST_REJECTED,
	PARK_PARAMETER_CHANGE_REQUEST_FAILURE,
	CREATE_PARK_PARAMETER_CHANGE_REQUEST,
	PARK_PARAMETER_CHANGE_REQUEST_CREATED,

	GET_PENDING_PARK_PARAMETER_CHANGE_REQUESTS,
	PENDING_PARK_PARAMETER_CHANGE_REQUESTS_RESULT,
	
	GET_REPORT_REQUEST,
	GET_REPORT_RESPONSE,
	
	OCCASIONAL_CUSTOMER_ACCESS_REQUEST,
	OCCASIONAL_CUSTOMER_ACCESS_RESPONSE,
	
	EMPLOYEE_LOGIN_REQUEST,
	EMPLOYEE_LOGIN_RESPONSE,

	SEARCH_SUBSCRIBER_REQUEST,
	SEARCH_SUBSCRIBER_RESPONSE,
	REGISTER_GUIDE_REQUEST,
	REGISTER_GUIDE_RESPONSE
}
